/*�룷�씤�듃 �뀒�씠釉�*/

CREATE SEQUENCE SEQ_POINT;

CREATE TABLE TBL_POINT(
	ID NUMBER CONSTRAINT PK_POINT PRIMARY KEY,
	MEMBER_ID NUMBER NOT NULL,
	DATA_ID NUMBER,
	POINT_HISTORY NUMBER NOT NULL,
	POINT_CATEGORY VARCHAR2(1000) NOT NULL CONSTRAINT CHECK_POINT_CATEGORY CHECK(POINT_CATEGORY IN('사용', '적립')),
	POINT_RECORD_DATE DATE DEFAULT SYSDATE
);

SELECT * FROM TBL_POINT;

DROP TABLE TBL_POINT;

/*TBL_POINT �뀒�씠釉� FK �꽕�젙*/
	ALTER TABLE TBL_POINT ADD CONSTRAINT FK_POINT_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID);
	
	ALTER TABLE TBL_POINT ADD CONSTRAINT FK_POINT_DATA FOREIGN KEY(DATA_ID)
	REFERENCES TBL_DATA(ID);
	
/*소영 포인트 TBL_POINT*/
INSERT INTO TBL_POINT
(ID, MEMBER_ID, POINT_HISTORY, POINT_CATEGORY)
VALUES(1,100, 2000, '적립');

INSERT INTO TBL_POINT
(ID, MEMBER_ID, DATA_ID, POINT_HISTORY, POINT_CATEGORY, POINT_RECORD_DATE)
VALUES(2, 100, 1001, 500, '적립', SYSDATE);