/*결제 테이블*/

CREATE SEQUENCE SEQ_PAY;

CREATE TABLE TBL_PAY(
	ID NUMBER CONSTRAINT PK_PAY PRIMARY KEY,
	MEMBER_ID NUMBER NOT NULL,
	DATA_ID NUMBER NOT NULL,
	PAY_TOTAL_PRICE NUMBER,
	PAY_POINT_USE NUMBER,
	PAY_STATUS CHAR(1) DEFAULT '1' CONSTRAINT CHECK_PAY CHECK(PAY_STATUS IN('0', '1')),
	PAY_REGISTER_DATE DATE DEFAULT SYSDATE
);

SELECT * FROM TBL_PAY;

DROP TABLE TBL_PAY;

/*TBL_PAY 테이블 FK 설정*/
	ALTER TABLE TBL_PAY ADD CONSTRAINT FK_PAY_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID);

	ALTER TABLE TBL_PAY ADD CONSTRAINT FK_PAY_DATA FOREIGN KEY(DATA_ID)
	REFERENCES TBL_DATA(ID);