/*프로젝트 파일 테이블 생성*/

CREATE SEQUENCE SEQ_PROJECT_FILE;

CREATE TABLE TBL_PROJECT_FILE(
	ID NUMBER CONSTRAINT PK_PROJECT_FILE PRIMARY KEY,
	PROJECT_ID NUMBER NOT NULL
);

SELECT * FROM TBL_PROJECT_FILE;

DROP TABLE TBL_PROJECT_FILE;

/*TBL_PROJECT_FILE 테이블 FK 설정*/
	ALTER TABLE TBL_PROJECT_FILE ADD CONSTRAINT FK_PROJECT_FILE_FILE FOREIGN KEY(ID)
	REFERENCES TBL_FILE(ID);

	ALTER TABLE TBL_PROJECT_FILE ADD CONSTRAINT FK_PROJECT_FILE_PROJECT FOREIGN KEY(PROJECT_ID)
	REFERENCES TBL_PROJECT(ID);

/*TBL_PROJECT_FILE 관련 더미 데이터*/
INSERT INTO WEGETHER.TBL_PROJECT_FILE
(ID, PROJECT_ID)
VALUES(1101, 94);	

INSERT INTO WEGETHER.TBL_PROJECT_FILE
(ID, PROJECT_ID)
VALUES(1102, 95);

INSERT INTO WEGETHER.TBL_PROJECT_FILE
(ID, PROJECT_ID)
VALUES(1103, 96);

INSERT INTO WEGETHER.TBL_PROJECT_FILE
(ID, PROJECT_ID)
VALUES(1104, 97);

INSERT INTO WEGETHER.TBL_PROJECT_FILE
(ID, PROJECT_ID)
VALUES(1105, 98);

INSERT INTO WEGETHER.TBL_PROJECT_FILE
(ID, PROJECT_ID)
VALUES(1106, 99);

INSERT INTO WEGETHER.TBL_PROJECT_FILE
(ID, PROJECT_ID)
VALUES(1107, 100);

INSERT INTO WEGETHER.TBL_PROJECT_FILE
(ID, PROJECT_ID)
VALUES(1108, 101);

INSERT INTO WEGETHER.TBL_PROJECT_FILE
(ID, PROJECT_ID)
VALUES(1109, 102);

INSERT INTO WEGETHER.TBL_PROJECT_FILE
(ID, PROJECT_ID)
VALUES(1110, 103);