/*자료 테이블 생성*/

CREATE SEQUENCE SEQ_DATA;

CREATE TABLE TBL_DATA(
	ID NUMBER CONSTRAINT PK_DATA PRIMARY KEY,
	MEMBER_ID NUMBER NOT NULL,
	DATA_TITLE VARCHAR2(1000) NOT NULL,
	DATA_CONTENT VARCHAR2(1000) NOT NULL,
	DATA_PRICE NUMBER DEFAULT 0,
	DATA_SCHOOL VARCHAR2(1000) NOT NULL,
	DATA_MAJOR VARCHAR2(1000) NOT NULL,
	DATA_READ_COUNT NUMBER DEFAULT 0,
	DATA_REGISTER_DATE DATE DEFAULT SYSDATE,
	DATA_UPDATE_DATE DATE DEFAULT SYSDATE
);

SELECT * FROM TBL_DATA;

DROP TABLE TBL_DATA;

/*TBL_DATA 테이블 FK 설정*/
	ALTER TABLE TBL_DATA ADD CONSTRAINT FK_DATA_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID);
	
INSERT INTO TBL_DATA
(ID, MEMBER_ID, DATA_TITLE, DATA_CONTENT, DATA_PRICE, DATA_SCHOOL, DATA_MAJOR, DATA_READ_COUNT)
VALUES(1000, 301, '자료 팔아요', '개꿀 자료', 2000, '서울대학교', 'computer', 0
);

INSERT INTO TBL_DATA
(ID, MEMBER_ID, DATA_TITLE, DATA_CONTENT, DATA_PRICE, DATA_SCHOOL, DATA_MAJOR, DATA_READ_COUNT)
VALUES(1001, 302, '에프터 이펙트 책 팜', '개꿀 자료', 2500, '홍익대학교', 'design', 15
);

INSERT INTO TBL_DATA
(ID, MEMBER_ID, DATA_TITLE, DATA_CONTENT, DATA_PRICE, DATA_SCHOOL, DATA_MAJOR, DATA_READ_COUNT)
VALUES(1002, 303, '체육수업모형', '체육과 자료', 4000, '한국체육대학교', 'sports', 2
);

INSERT INTO TBL_DATA
(ID, MEMBER_ID, DATA_TITLE, DATA_CONTENT, DATA_PRICE, DATA_SCHOOL, DATA_MAJOR, DATA_READ_COUNT)
VALUES(1003, 304, '책 많이 사세여', '바이오', 10000, '고려대학교', 'biology', 1
);

INSERT INTO TBL_DATA
(ID, MEMBER_ID, DATA_TITLE, DATA_CONTENT, DATA_PRICE, DATA_SCHOOL, DATA_MAJOR, DATA_READ_COUNT)
VALUES(1004, 100, '인포그래픽 사실 분 ~', '책 팔아용', 5000, '단국대학교', 'design', 5
);

INSERT INTO TBL_DATA
(ID, MEMBER_ID, DATA_TITLE, DATA_CONTENT, DATA_PRICE, DATA_SCHOOL, DATA_MAJOR, DATA_READ_COUNT)
VALUES(1005, 100, '이론책 팔아요', '책 팔아용', 8000, '연세대학교', 'chemistry', 5
);

INSERT INTO TBL_DATA
(ID, MEMBER_ID, DATA_TITLE, DATA_CONTENT, DATA_PRICE, DATA_SCHOOL, DATA_MAJOR, DATA_READ_COUNT)
VALUES(1006, 305, '세상을 바꾼 화학', '책 팔아용', 4600, '연세대학교', 'chemistry', 0
);

INSERT INTO TBL_DATA
(ID, MEMBER_ID, DATA_TITLE, DATA_CONTENT, DATA_PRICE, DATA_SCHOOL, DATA_MAJOR, DATA_READ_COUNT)
VALUES(1007, 306, '이것저것', '책 팔아용', 4800, '서강대학교', 'machine', 2
);

INSERT INTO TBL_DATA
(ID, MEMBER_ID, DATA_TITLE, DATA_CONTENT, DATA_PRICE, DATA_SCHOOL, DATA_MAJOR, DATA_READ_COUNT)
VALUES(1008, 307, '이론 책입니다', '팜', 3000, '건국대학교', 'machine', 0
);

INSERT INTO TBL_DATA
(ID, MEMBER_ID, DATA_TITLE, DATA_CONTENT, DATA_PRICE, DATA_SCHOOL, DATA_MAJOR, DATA_READ_COUNT)
VALUES(1009, 308, '기초이론 ~!', '팜', 1500, '성균관대학교', 'engineering', 4
);

INSERT INTO TBL_DATA
(ID, MEMBER_ID, DATA_TITLE, DATA_CONTENT, DATA_PRICE, DATA_SCHOOL, DATA_MAJOR, DATA_READ_COUNT)
VALUES(1010, 309, '디자인 모여 ~!~!!', '팜', 2000, '서울예술대학교', 'design', 3
);

INSERT INTO TBL_DATA
(ID, MEMBER_ID, DATA_TITLE, DATA_CONTENT, DATA_PRICE, DATA_SCHOOL, DATA_MAJOR, DATA_READ_COUNT)
VALUES(1011, 100, '수학과 자료', '팜', 10000, '서울대학교', 'math', 2
);

INSERT INTO TBL_DATA
(ID, MEMBER_ID, DATA_TITLE, DATA_CONTENT, DATA_PRICE, DATA_SCHOOL, DATA_MAJOR, DATA_READ_COUNT)
VALUES(1012, 100, '자료', '팜', 4000, '서울대학교', 'sports', 0
);

INSERT INTO TBL_DATA
(ID, MEMBER_ID, DATA_TITLE, DATA_CONTENT, DATA_PRICE, DATA_SCHOOL, DATA_MAJOR, DATA_READ_COUNT)
VALUES(1013, 301, '체육과 책 살 사람 ~', '팜', 4400, '용인대학교', 'sports', 10
);

INSERT INTO TBL_DATA
(ID, MEMBER_ID, DATA_TITLE, DATA_CONTENT, DATA_PRICE, DATA_SCHOOL, DATA_MAJOR, DATA_READ_COUNT)
VALUES(1014, 302, '체육과 자료', '팜', 4400, '용인대학교', 'sports', 10
);

INSERT INTO TBL_DATA
(ID, MEMBER_ID, DATA_TITLE, DATA_CONTENT, DATA_PRICE, DATA_SCHOOL, DATA_MAJOR, DATA_READ_COUNT)
VALUES(1015, 302, '미디어 자료', '팜', 4400, '용인대학교', 'media', 5
);

INSERT INTO TBL_DATA
(ID, MEMBER_ID, DATA_TITLE, DATA_CONTENT, DATA_PRICE, DATA_SCHOOL, DATA_MAJOR, DATA_READ_COUNT)
VALUES(1016, 303, '엔지니어 자료', '팜', 2000, '성균관대학교', 'engineering', 0
);

INSERT INTO TBL_DATA
(ID, MEMBER_ID, DATA_TITLE, DATA_CONTENT, DATA_PRICE, DATA_SCHOOL, DATA_MAJOR, DATA_READ_COUNT)
VALUES(1017, 304, '실음과 자료 음악학 개론', '팜', 1500, '예원예술대학교', 'applied_music', 20
);

INSERT INTO TBL_DATA
(ID, MEMBER_ID, DATA_TITLE, DATA_CONTENT, DATA_PRICE, DATA_SCHOOL, DATA_MAJOR, DATA_READ_COUNT)
VALUES(1018, 305, '화성학을 아십니까', '팝니다', 5000, '한국예술종합대학교', 'applied_music', 10
);

INSERT INTO TBL_DATA
(ID, MEMBER_ID, DATA_TITLE, DATA_CONTENT, DATA_PRICE, DATA_SCHOOL, DATA_MAJOR, DATA_READ_COUNT)
VALUES(1019, 306, '생물학관련 자료입니다', '팝니다', 3000, '서울대학교', 'biology', 22
);

INSERT INTO TBL_DATA
(ID, MEMBER_ID, DATA_TITLE, DATA_CONTENT, DATA_PRICE, DATA_SCHOOL, DATA_MAJOR, DATA_READ_COUNT)
VALUES(1020, 306, '컴공과 자료', '팝니다', 3000, '고려대학교', 'computer', 1
);

INSERT INTO TBL_DATA
(ID, MEMBER_ID, DATA_TITLE, DATA_CONTENT, DATA_PRICE, DATA_SCHOOL, DATA_MAJOR, DATA_READ_COUNT)
VALUES(1021, 306, '컴공과 자료입니당', '팝니다', 2000, '연세대학교', 'computer', 3
);

INSERT INTO TBL_DATA
(ID, MEMBER_ID, DATA_TITLE, DATA_CONTENT, DATA_PRICE, DATA_SCHOOL, DATA_MAJOR, DATA_READ_COUNT)
VALUES(1022, 307, '사실분?', '팝니다', 2700, '연세대학교', 'computer', 3
);

INSERT INTO TBL_DATA
(ID, MEMBER_ID, DATA_TITLE, DATA_CONTENT, DATA_PRICE, DATA_SCHOOL, DATA_MAJOR, DATA_READ_COUNT)
VALUES(1023, 308, '컴터 관련 자료예욤', '팝니다', 4000, '건국대학교', 'computer', 10
);

INSERT INTO TBL_DATA
(ID, MEMBER_ID, DATA_TITLE, DATA_CONTENT, DATA_PRICE, DATA_SCHOOL, DATA_MAJOR, DATA_READ_COUNT)
VALUES(1024, 308, '디자인과 자료입니다', '팝니다', 5000, '건국대학교', 'design', 0
);

INSERT INTO TBL_DATA
(ID, MEMBER_ID, DATA_TITLE, DATA_CONTENT, DATA_PRICE, DATA_SCHOOL, DATA_MAJOR, DATA_READ_COUNT)
VALUES(1025, 309, '시디과 자료', '팝니다', 5000, '백석대학교', 'design', 4
);

INSERT INTO TBL_DATA
(ID, MEMBER_ID, DATA_TITLE, DATA_CONTENT, DATA_PRICE, DATA_SCHOOL, DATA_MAJOR, DATA_READ_COUNT)
VALUES(1026, 308, '3개 팔아염', '팝니다', 9000, '백석대학교', 'computer', 30
);

INSERT INTO TBL_DATA
(ID, MEMBER_ID, DATA_TITLE, DATA_CONTENT, DATA_PRICE, DATA_SCHOOL, DATA_MAJOR, DATA_READ_COUNT)
VALUES(1027, 309, '공학도 있나요?', '팔아요', 4000, '건국대학교', 'engineering', 20
);