/*�뙆�씪 �뀒�씠釉� �깮�꽦*/

CREATE SEQUENCE SEQ_FILE;

CREATE TABLE TBL_FILE(
	ID NUMBER CONSTRAINT PK_FILE PRIMARY KEY,
	FILE_PATH VARCHAR2(1000) NOT NULL,
	FILE_UUID VARCHAR2(1000) NOT NULL,
	FILE_NAME VARCHAR2(1000) NOT NULL,
	FILE_SIZE NUMBER NOT NULL,
	FILE_TYPE VARCHAR2(1000) DEFAULT 'NON_REPRESENTATIVE'
	CONSTRAINT CHECK_FILE_TYPE CHECK(FILE_TYPE IN ('NON_REPRESENTATIVE', 'REPRESENTATIVE'))
);

ALTER TABLE TBL_FILE
    DROP CONSTRAINT CHECK_FILE_TYPE

ALTER TABLE TBL_FILE
    ADD CONSTRAINT CHECK_FILE_TYPE
    CHECK (FILE_TYPE IN ('REPRESENTATIVE', 'NON_REPRESENTATIVE', 'CONTENT_REPRESENTATIVE'))

SELECT * FROM TBL_FILE;

DROP TABLE TBL_FILE;



/*자료 FILE 1001 ~ 1100*/
INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1001, '2023/05/31', 'data', 'applied-music-01.png', 55, 'REPRESENTATIVE'
);

INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1002, '2023/05/31', 'data', 'applied-music-02.png', 55, 'REPRESENTATIVE'
);

INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1003, '2023/05/31', 'data', 'biology-01.png', 55, 'REPRESENTATIVE'
);


INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1004, '2023/05/31', 'data', 'biology-02.png', 55, 'REPRESENTATIVE'
);


INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1005, '2023/05/31', 'data', 'chemistry-01.png', 55, 'REPRESENTATIVE'
);


INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1006, '2023/05/31', 'data', 'chemistry-02.png', 55, 'REPRESENTATIVE'
);


INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1007, '2023/05/31', 'data', 'computer-01.png', 55, 'REPRESENTATIVE'
);


INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1008, '2023/05/31', 'data', 'computer-02.png', 55, 'REPRESENTATIVE'
);


INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1009, '2023/05/31', 'data', 'computer-03.png', 55, 'REPRESENTATIVE'
);


INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1010, '2023/05/31', 'data', 'computer-04.png', 55, 'REPRESENTATIVE'
);


INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1011, '2023/05/31', 'data', 'computer-05.png', 55, 'REPRESENTATIVE'
);


INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1012, '2023/05/31', 'data', 'computer-06.png', 55, 'REPRESENTATIVE'
);


INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1013, '2023/05/31', 'data', 'design-01.png', 55, 'REPRESENTATIVE'
);


INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1014, '2023/05/31', 'data', 'design-02.png', 55, 'REPRESENTATIVE'
);


INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1015, '2023/05/31', 'data', 'design-03.png', 55, 'REPRESENTATIVE'
);


INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1016, '2023/05/31', 'data', 'design-04.png', 55, 'REPRESENTATIVE'
);

INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1017, '2023/05/31', 'data', 'design-05.png', 55, 'REPRESENTATIVE'
);


INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1018, '2023/05/31', 'data', 'engineering-01.png', 55, 'REPRESENTATIVE'
);


INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1019, '2023/05/31', 'data', 'engineering-02.png', 55, 'REPRESENTATIVE'
);


INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1020, '2023/05/31', 'data', 'engineering-03.png', 55, 'REPRESENTATIVE'
);

INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1021, '2023/05/31', 'data', 'machine-01.png', 55, 'REPRESENTATIVE'
);

INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1022, '2023/05/31', 'data', 'machine-02.png', 55, 'REPRESENTATIVE'
);

INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1023, '2023/05/31', 'data', 'math-01.png', 55, 'REPRESENTATIVE'
);

INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1024, '2023/05/31', 'data', 'media-01.png', 55, 'REPRESENTATIVE'
);

INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1025, '2023/05/31', 'data', 'sports-01.png', 55, 'REPRESENTATIVE'
);

INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1026, '2023/05/31', 'data', 'sports-02.png', 55, 'REPRESENTATIVE'
);

INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1027, '2023/05/31', 'data', 'sports-03.png', 55, 'REPRESENTATIVE'
);

INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1028, '2023/05/31', 'data', 'sports-04.png', 55, 'REPRESENTATIVE'
-------------------------------------------- 유미 여기 FILE 더미 넣어야 함 -------------------------------------------


/*프로젝트 FILE 1101 ~ 1200*/
INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1101   ,'2023/05/31', 'id', '프로젝트1.png', 0, 'REPRESENTATIVE')

INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1102   ,'2023/05/31', 'id', '프로젝트2.png', 0, 'REPRESENTATIVE')

INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1103   ,'2023/05/31', 'id', '프로젝트3.png', 0, 'REPRESENTATIVE')

INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1104   ,'2023/05/31', 'id', '프로젝트4.png', 0, 'REPRESENTATIVE')

INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1105   ,'2023/05/31', 'id', '프로젝트5.png', 0, 'REPRESENTATIVE')

INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1106   ,'2023/05/31', 'id', '프로젝트6.png', 0, 'REPRESENTATIVE')

INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1107   ,'2023/05/31', 'id', '프로젝트7.png', 0, 'REPRESENTATIVE')

INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1108   ,'2023/05/31', 'id', '프로젝트8.png', 0, 'REPRESENTATIVE')

INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1109   ,'2023/05/31', 'id', '프로젝트9.png', 0, 'REPRESENTATIVE')

INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1110   ,'2023/05/31', 'id', '프로젝트10.png', 0, 'REPRESENTATIVE')


/*커뮤니티 FILE 1201 ~ 1300*/
INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1201, '2023/05/31', 'c', 'board15picture1.png', 55, 'REPRESENTATIVE'
);

INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1202, '2023/05/31', 'c', 'board14picture1.png', 55, 'REPRESENTATIVE');

INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1203, '2023/05/31', 'c', 'board13picture1.png', 55, 'REPRESENTATIVE');

INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1204, '2023/05/31', 'c', 'board12picture1.png', 55, 'REPRESENTATIVE');

INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1205, '2023/05/31', 'c', 'board11picture1.png', 55, 'REPRESENTATIVE');

INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1206, '2023/05/31', 'c', 'board10picture1.png', 55, 'REPRESENTATIVE');

INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1207, '2023/05/31', 'c', 'board10picture2.png', 55, 'NON_REPRESENTATIVE');

INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1208, '2023/05/31', 'c', 'board9picture1.png', 55, 'REPRESENTATIVE');

INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1209, '2023/05/31', 'c', 'board9picture2.png', 55, 'NON_REPRESENTATIVE');

INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1210, '2023/05/31', 'c', 'board9picture3.png', 55, 'NON_REPRESENTATIVE');

INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1211, '2023/05/31', 'c', 'board8picture1.png', 55, 'REPRESENTATIVE');

INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1212, '2023/05/31', 'c', 'board7picture1.png', 55, 'REPRESENTATIVE');

INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1213, '2023/05/31', 'c', 'board6picture1.png', 55, 'REPRESENTATIVE');

INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1214, '2023/05/31', 'c', 'board6picture2.png', 55, 'NON_REPRESENTATIVE');

INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1215, '2023/05/31', 'c', 'board6picture3.png', 55, 'NON_REPRESENTATIVE');

INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1216, '2023/05/31', 'c', 'board5picture1.png', 55, 'REPRESENTATIVE');

INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1217, '2023/05/31', 'c', 'board5picture2.png', 55, 'NON_REPRESENTATIVE');

INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1218, '2023/05/31', 'c', 'board5picture3.png', 55, 'NON_REPRESENTATIVE');

INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1219, '2023/05/31', 'c', 'board4picture1.png', 55, 'REPRESENTATIVE');

INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1220, '2023/05/31', 'c', 'board3picture1.png', 55, 'REPRESENTATIVE');

INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1221, '2023/05/31', 'c', 'board2picture1.png', 55, 'REPRESENTATIVE');

INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1222, '2023/05/31', 'c', 'board1picture1.png', 55, 'REPRESENTATIVE');

INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1223, '2023/05/31', 'c', 'board1picture2.png', 55, 'NON_REPRESENTATIVE');

INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1224, '2023/05/31', 'c', 'board1picture3.png', 55, 'NON_REPRESENTATIVE');


/*강연 FILE 1301 ~ 1400*/
/*게시판 1 파일*/
INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1301, '2023/05/20', 'a', '대표이미지1.png', 5000, 'REPRESENTATIVE');

INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1302, '2023/05/20', 'a', '제목1.png', 5000, 'NON_REPRESENTATIVE');

INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1303, '2023/05/20', 'a', '내용1.png', 5000, 'CONTENT_REPRESENTATIVE');


/*게시판 2 파일*/
INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1304, '2023/05/20', 'b', '대표이미지2.png', 5000, 'REPRESENTATIVE');
INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1305, '2023/05/20', 'b', '제목2.png', 5000, 'NON_REPRESENTATIVE');
INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1306, '2023/05/20', 'b', '내용2.png', 5000, 'CONTENT_REPRESENTATIVE');

/*게시판 3 파일*/
INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1307, '2023/05/20', 'c', '대표이미지3.png', 5000, 'REPRESENTATIVE');
INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1308, '2023/05/20', 'c', '제목3.png', 5000, 'NON_REPRESENTATIVE');
INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1309, '2023/05/20', 'c', '내용3.png', 5000, 'CONTENT_REPRESENTATIVE');

/*게시판 4 파일*/
INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1310, '2023/05/20', 'd', '대표이미지4.png', 5000, 'REPRESENTATIVE');
INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1311, '2023/05/20', 'd', '제목4.png', 5000, 'NON_REPRESENTATIVE');
INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1312, '2023/05/20', 'd', '내용4.png', 5000, 'CONTENT_REPRESENTATIVE');

/*게시판 5 파일*/
INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1313, '2023/05/20', 'e', '대표이미지5.png', 5000, 'REPRESENTATIVE');
INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1314, '2023/05/20', 'e', '제목5.png', 5000, 'NON_REPRESENTATIVE');
INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1315, '2023/05/20', 'e', '내용5.png', 5000, 'CONTENT_REPRESENTATIVE');

/*공지사항 FILE 1401 ~ 1500*/
/*공지사항 FILE 1401 ~ 1500*/
INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1401, '2023/05/31', 'id', '공지사항1.png', 0, 'REPRESENTATIVE');

INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1402, '2023/05/31', 'id', '공지사항2.png', 0, 'REPRESENTATIVE');

INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1403, '2023/05/31', 'id', '공지사항3.png', 0, 'REPRESENTATIVE');

INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1404, '2023/05/31', 'id', '공지사항4.png', 0, 'REPRESENTATIVE');

INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1405, '2023/05/31', 'id', '공지사항5.png', 0, 'REPRESENTATIVE');

INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1406, '2023/05/31', 'id', '공지사항6.png', 0, 'REPRESENTATIVE');

INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1407, '2023/05/31', 'id', '공지사항7.png', 0, 'REPRESENTATIVE');

INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1408, '2023/05/31', 'id', '공지사항8.png', 0, 'REPRESENTATIVE');

INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1409, '2023/05/31', 'id', '공지사항9.png', 0, 'REPRESENTATIVE');

INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1410, '2023/05/31', 'id', '공지사항10.png', 0, 'REPRESENTATIVE');

INSERT INTO TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1411, '2023/05/31', 'id', '공지사항상세1.png', 0, 'NON_REPRESENTATIVE');
