/*답변 테이블 생성*/

CREATE SEQUENCE SEQ_ANSWER;

CREATE TABLE TBL_ANSWER(
	ID NUMBER CONSTRAINT PK_ANSWER PRIMARY KEY,
	INQUIRY_ID NUMBER NOT NULL,
	ANSWER_CONTENT VARCHAR2(1000) NOT NULL,
	ANSWER_REGISTER_DATE DATE DEFAULT SYSDATE,
	ANSWER_UPDATE_DATE DATE DEFAULT SYSDATE
);

SELECT * FROM TBL_ANSWER;

DROP TABLE TBL_ANSWER;

/*TBL_ANSWER 테이블 FK 설정*/
	ALTER TABLE TBL_ANSWER ADD CONSTRAINT FK_ANSWER_INQUIRY FOREIGN KEY(INQUIRY_ID)
	REFERENCES TBL_INQUIRY(ID);
	
INSERT INTO TBL_ANSWER
(ID, INQUIRY_ID, ANSWER_CONTENT)
VALUES(100, 95, '안녕하세요. 위게더 입니다. 먼저 위게더에 사이트 이용에 소중한 시간 내어주신 점 감사합니다. 위게더는 카카오, 네이버 계정 모두 사용이 가능합니다! 다른 문의 사항이 있으시면, 추가로 문의 해주시기 바랍니다. 항상 감사합니다.');\

INSERT INTO TBL_ANSWER
(ID, INQUIRY_ID, ANSWER_CONTENT)
VALUES(99, 94, '문의하신 답변 내용 입니다.');

INSERT INTO TBL_ANSWER
(ID, INQUIRY_ID, ANSWER_CONTENT)
VALUES(98, 93, '문의하신 답변 내용 입니다.');

INSERT INTO TBL_ANSWER
(ID, INQUIRY_ID, ANSWER_CONTENT)
VALUES(97, 92, '문의하신 답변 내용 입니다.');

INSERT INTO TBL_ANSWER
(ID, INQUIRY_ID, ANSWER_CONTENT)
VALUES(96, 91, '안녕하세요. 위게더 입니다. 먼저 위게더에 사이트 이용에 소중한 시간 내어주신 점 감사합니다. 위게더에서 자료를 구매하시면, 관련 자료를 다운로드 받아보실 수 있습니다. 다른 문의 사항이 있으시면, 추가로 문의 해주시기 바랍니다. 감사합니다.');
