/*카드 등록 테이블 생성*/

CREATE SEQUENCE SEQ_CARD;

CREATE TABLE TBL_CARD(
	ID NUMBER CONSTRAINT PK_CARD PRIMARY KEY,
	MEMBER_ID NUMBER NOT NULL,
	CARD_NUMBER VARCHAR2(1000) NOT NULL,
	CARD_BIRTH_DATE VARCHAR2(1000) NOT NULL,
	MEMBER_BIRTHDATE VARCHAR2(1000) NOT NULL,
	CARD_PASSWORD VARCHAR2(1000) NOT NULL,
	CARD_REGISTER_DATE DATE DEFAULT SYSDATE
);

ALTER TABLE TBL_CARD ADD CARD_EXPIRE_DATE VARCHAR(1000) NOT NULL

ALTER TABLE TBL_CARD DROP COLUMN CARD_BIRTH_DATE

SELECT * FROM TBL_CARD;

DROP TABLE TBL_CARD;

/*TBL_CARD 테이블 FK 설정*/
	ALTER TABLE TBL_CARD ADD CONSTRAINT FK_CARD_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID);
	
INSERT INTO TBL_CARD
(ID, MEMBER_ID, CARD_NUMBER, CARD_EXPIRE_DATE, MEMBER_BIRTHDATE, CARD_PASSWORD, CARD_REGISTER_DATE)
VALUES(SEQ_CARD.NEXTVAL, 100, '1111222233334444', '0525', '000210', '1234', SYSDATE
);

INSERT INTO TBL_CARD
(ID, MEMBER_ID, CARD_NUMBER, CARD_EXPIRE_DATE, MEMBER_BIRTHDATE, CARD_PASSWORD, CARD_REGISTER_DATE)
VALUES(SEQ_CARD.NEXTVAL, 100, '1234567812345678', '0526', '000210', '1234',SYSDATE);

INSERT INTO TBL_CARD
(ID, MEMBER_ID, CARD_NUMBER, CARD_EXPIRE_DATE, MEMBER_BIRTHDATE, CARD_PASSWORD, CARD_REGISTER_DATE)
VALUES(SEQ_CARD.NEXTVAL, 100, '123456789012', '1028', '000210', '2559', SYSDATE);