/*강연 테이블 생성*/

CREATE SEQUENCE SEQ_LECTURE;

CREATE TABLE TBL_LECTURE(
	ID NUMBER CONSTRAINT PK_LECTURE PRIMARY KEY,
	LECTURE_TITLE VARCHAR2(1000) NOT NULL,
	LECTURE_CONTENT VARCHAR2(1000) NOT NULL,
	LECTURE_DATE VARCHAR2(1000) NOT NULL,
	LECTURE_TIME VARCHAR2(1000) NOT NULL,
	LECTURE_LOCATION VARCHAR2(1000) NOT NULL,
	LECTURE_TOTAL_PERSONNEL NUMBER NOT NULL,
	LECTURE_REGISTER_DATE DATE DEFAULT SYSDATE,
	LECTURE_UPDATE_DATE DATE DEFAULT SYSDATE
);

SELECT * FROM TBL_LECTURE;

DROP TABLE TBL_LECTURE;


/*TBL_LECTURE 관련 더미 데이터*/
INSERT INTO TBL_LECTURE
(ID, LECTURE_TITLE, LECTURE_CONTENT, LECTURE_DATE, LECTURE_TIME, LECTURE_LOCATION, LECTURE_TOTAL_PERSONNEL)
VALUES(1, '대학 입시 정보박람회', '특이사항 없습니다', '2023년 6월25일', '오후3시부터 5시', '삼성 코엑스', 100);

INSERT INTO TBL_LECTURE
(ID, LECTURE_TITLE, LECTURE_CONTENT, LECTURE_DATE, LECTURE_TIME, LECTURE_LOCATION, LECTURE_TOTAL_PERSONNEL)
VALUES(2, '대학 입시 정보공유 토론회', '입시준비하는 사람들에겐 황금같은 기회입니다', '2023년 6월24일', '오후5시부터 7시', '삼성 코엑스', 200);

INSERT INTO TBL_LECTURE
(ID, LECTURE_TITLE, LECTURE_CONTENT, LECTURE_DATE, LECTURE_TIME, LECTURE_LOCATION, LECTURE_TOTAL_PERSONNEL)
VALUES(3, '미대 입시 작품 설명회', '미대에 관심있으면 참여하세요', '2023년 6월25일', '오후2시부터 5시', '예술의 전당 2층 강당', 200);

INSERT INTO TBL_LECTURE
(ID, LECTURE_TITLE, LECTURE_CONTENT, LECTURE_DATE, LECTURE_TIME, LECTURE_LOCATION, LECTURE_TOTAL_PERSONNEL)
VALUES(4, '서울대 컴퓨터공학과 출신 강의', '좋은 기회입니다 잡으세요!', '2023년 6월23일', '오후5시부터 7시', '올림픽 공원 1B 경기장', 300);

INSERT INTO TBL_LECTURE
(ID, LECTURE_TITLE, LECTURE_CONTENT, LECTURE_DATE, LECTURE_TIME, LECTURE_LOCATION, LECTURE_TOTAL_PERSONNEL)
VALUES(5, '2030을 위한 친환경 설명회', '친환경 삶을 위해!', '2023년 7월2일', '오후5시부터 7시', '잠실운동장1A 경기장', 400);

