/*자료 파일 테이블 생성*/

CREATE SEQUENCE SEQ_DATA_FILE;

CREATE TABLE TBL_DATA_FILE(
	ID NUMBER CONSTRAINT PK_DATA_FILE PRIMARY KEY,
	DATA_ID NUMBER NOT NULL
);

SELECT * FROM TBL_DATA_FILE;

DROP TABLE TBL_DATA_FILE;

/*TBL_DATA_FILE 테이블 FK 설정*/
	ALTER TABLE TBL_DATA_FILE ADD CONSTRAINT FK_DATA_FILE_FILE FOREIGN KEY(ID)
	REFERENCES TBL_FILE(ID);

	ALTER TABLE TBL_DATA_FILE ADD CONSTRAINT FK_DATA_FILE_DATA FOREIGN KEY(DATA_ID)
	REFERENCES TBL_DATA(ID);


------------------ 실음과 --------------------
INSERT INTO TBL_DATA_FILE
(ID, DATA_ID)
VALUES(1001, 1017);

INSERT INTO TBL_DATA_FILE
(ID, DATA_ID)
VALUES(1002, 1018);

----------------- 바이오 -------------------------

INSERT INTO TBL_DATA_FILE
(ID, DATA_ID)
VALUES(1003, 1003);

INSERT INTO TBL_DATA_FILE
(ID, DATA_ID)
VALUES(1004, 1019);

------------------- 화학과 ----------------------

INSERT INTO TBL_DATA_FILE
(ID, DATA_ID)
VALUES(1005, 1005);

INSERT INTO TBL_DATA_FILE
(ID, DATA_ID)
VALUES(1006, 1006);

------------------ 컴공 -----------------------

INSERT INTO TBL_DATA_FILE
(ID, DATA_ID)
VALUES(1007, 1000);

INSERT INTO TBL_DATA_FILE
(ID, DATA_ID)
VALUES(1008, 1020);

INSERT INTO TBL_DATA_FILE
(ID, DATA_ID)
VALUES(1009, 1021);

INSERT INTO TBL_DATA_FILE
(ID, DATA_ID)
VALUES(1010, 1022);

INSERT INTO TBL_DATA_FILE
(ID, DATA_ID)
VALUES(1011, 1023);

INSERT INTO TBL_DATA_FILE
(ID, DATA_ID)
VALUES(1012, 1026);

-------------------- 디자인 -------------------

INSERT INTO TBL_DATA_FILE
(ID, DATA_ID)
VALUES(1013, 1001);

INSERT INTO TBL_DATA_FILE
(ID, DATA_ID)
VALUES(1014, 1004);

INSERT INTO TBL_DATA_FILE
(ID, DATA_ID)
VALUES(1015, 1010);

INSERT INTO TBL_DATA_FILE
(ID, DATA_ID)
VALUES(1016, 1024);

INSERT INTO TBL_DATA_FILE
(ID, DATA_ID)
VALUES(1017, 1025);

------------------------- 엔지니어링 --------------------------

INSERT INTO TBL_DATA_FILE
(ID, DATA_ID)
VALUES(1018, 1009);

INSERT INTO TBL_DATA_FILE
(ID, DATA_ID)
VALUES(1019, 1016);

INSERT INTO TBL_DATA_FILE
(ID, DATA_ID)
VALUES(1020, 1027);

--------------------------- 기계 -------------------------------

INSERT INTO TBL_DATA_FILE
(ID, DATA_ID)
VALUES(1021, 1007);

INSERT INTO TBL_DATA_FILE
(ID, DATA_ID)
VALUES(1022, 1008);

---------------------------- 수학 -------------------------------

INSERT INTO TBL_DATA_FILE
(ID, DATA_ID)
VALUES(1023, 1011);

---------------------------- 미디어 --------------------------------

INSERT INTO TBL_DATA_FILE
(ID, DATA_ID)
VALUES(1024, 1015);

----------------------------- 체육과 --------------------------

INSERT INTO TBL_DATA_FILE
(ID, DATA_ID)
VALUES(1025, 1002);

INSERT INTO TBL_DATA_FILE
(ID, DATA_ID)
VALUES(1026, 1012);

INSERT INTO TBL_DATA_FILE
(ID, DATA_ID)
VALUES(1027, 1013);

INSERT INTO TBL_DATA_FILE
(ID, DATA_ID)
VALUES(1028, 1014);

INSERT INTO TBL_DATA_FILE
(ID, DATA_ID)
VALUES(1012, 1020);

INSERT INTO TBL_DATA_FILE
(ID, DATA_ID)
VALUES(1012, 1020);

INSERT INTO TBL_DATA_FILE
(ID, DATA_ID)
VALUES(1012, 1020);