/*커뮤니티 댓글 테이블 생성*/

CREATE SEQUENCE SEQ_COMMUNITY_REPLY;

CREATE TABLE TBL_COMMUNITY_REPLY(
	ID NUMBER CONSTRAINT PK_COMMUNITY_REPLY PRIMARY KEY,
	MEMBER_ID NUMBER NOT NULL,
	COMMUNITY_ID NUMBER NOT NULL
);

SELECT * FROM TBL_COMMUNITY_REPLY;

DROP TABLE TBL_COMMUNITY_REPLY;

/*TBL_COMMUNITY_REPLY 테이블 FK 설정*/
	ALTER TABLE TBL_COMMUNITY_REPLY ADD CONSTRAINT FK_COMMUNITY_REPLY_REPLY FOREIGN KEY(ID)
	REFERENCES TBL_REPLY(ID);

	ALTER TABLE TBL_COMMUNITY_REPLY ADD CONSTRAINT FK_COMMUNITY_REPLY_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID);

	ALTER TABLE TBL_COMMUNITY_REPLY ADD CONSTRAINT FK_COMMUNITY_REPLY_COMMUNITY FOREIGN KEY(COMMUNITY_ID)
	REFERENCES TBL_COMMUNITY(ID);

---------------------- TBL_COMMUNITY_REPLY 더미데이터 ----------------------------

INSERT INTO WEGETHER.TBL_COMMUNITY_REPLY
(ID, MEMBER_ID, COMMUNITY_ID)
VALUES(1201, 309, 15);

INSERT INTO WEGETHER.TBL_COMMUNITY_REPLY
(ID, MEMBER_ID, COMMUNITY_ID)
VALUES(1202, 308, 15);

INSERT INTO WEGETHER.TBL_COMMUNITY_REPLY
(ID, MEMBER_ID, COMMUNITY_ID)
VALUES(1203, 307, 15);

INSERT INTO WEGETHER.TBL_COMMUNITY_REPLY
(ID, MEMBER_ID, COMMUNITY_ID)
VALUES(1204, 306, 15);

INSERT INTO WEGETHER.TBL_COMMUNITY_REPLY
(ID, MEMBER_ID, COMMUNITY_ID)
VALUES(1205, 305, 15);

INSERT INTO WEGETHER.TBL_COMMUNITY_REPLY
(ID, MEMBER_ID, COMMUNITY_ID)
VALUES(1206, 304, 15);

INSERT INTO WEGETHER.TBL_COMMUNITY_REPLY
(ID, MEMBER_ID, COMMUNITY_ID)
VALUES(1207, 303, 15);

INSERT INTO WEGETHER.TBL_COMMUNITY_REPLY
(ID, MEMBER_ID, COMMUNITY_ID)
VALUES(1208, 302, 15);

INSERT INTO WEGETHER.TBL_COMMUNITY_REPLY
(ID, MEMBER_ID, COMMUNITY_ID)
VALUES(1209, 301, 15);
