/*而ㅻ�ㅻ땲�떚 �뙆�씪 �뀒�씠釉� �깮�꽦*/

CREATE SEQUENCE SEQ_COMMUNITY_FILE;

CREATE TABLE TBL_COMMUNITY_FILE(
	ID NUMBER CONSTRAINT PK_COMMUNITY_FILE PRIMARY KEY,
	COMMUNITY_ID NUMBER NOT NULL
);

SELECT * FROM TBL_COMMUNITY_FILE;

DROP TABLE TBL_COMMUNITY_FILE;

/*TBL_COMMUNITY_FILE �뀒�씠釉� FK �꽕�젙*/
	ALTER TABLE TBL_COMMUNITY_FILE ADD CONSTRAINT FK_COMMUNITY_FILE_FILE FOREIGN KEY(ID)
	REFERENCES TBL_FILE(ID) ON DELETE CASCADE;

	ALTER TABLE TBL_COMMUNITY_FILE ADD CONSTRAINT FK_COMMUNITY_FILE_COMMUNITY FOREIGN KEY(COMMUNITY_ID)
	REFERENCES TBL_COMMUNITY(ID) ON DELETE CASCADE;


INSERT INTO WEGETHER.TBL_COMMUNITY_FILE
(ID, COMMUNITY_ID)
VALUES(1201, 1);


INSERT INTO WEGETHER.TBL_COMMUNITY_FILE
(ID, COMMUNITY_ID)
VALUES(1202, 2);


INSERT INTO WEGETHER.TBL_COMMUNITY_FILE
(ID, COMMUNITY_ID)
VALUES(1203, 3);


INSERT INTO WEGETHER.TBL_COMMUNITY_FILE
(ID, COMMUNITY_ID)
VALUES(1204, 4);


INSERT INTO WEGETHER.TBL_COMMUNITY_FILE
(ID, COMMUNITY_ID)
VALUES(1205, 5);


INSERT INTO WEGETHER.TBL_COMMUNITY_FILE
(ID, COMMUNITY_ID)
VALUES(1206, 6);


INSERT INTO WEGETHER.TBL_COMMUNITY_FILE
(ID, COMMUNITY_ID)
VALUES(1207, 6);


INSERT INTO WEGETHER.TBL_COMMUNITY_FILE
(ID, COMMUNITY_ID)
VALUES(1208, 7);


INSERT INTO WEGETHER.TBL_COMMUNITY_FILE
(ID, COMMUNITY_ID)
VALUES(1209, 7);


INSERT INTO WEGETHER.TBL_COMMUNITY_FILE
(ID, COMMUNITY_ID)
VALUES(1210, 7);


INSERT INTO WEGETHER.TBL_COMMUNITY_FILE
(ID, COMMUNITY_ID)
VALUES(1211, 8);


INSERT INTO WEGETHER.TBL_COMMUNITY_FILE
(ID, COMMUNITY_ID)
VALUES(1212, 9);

INSERT INTO WEGETHER.TBL_COMMUNITY_FILE
(ID, COMMUNITY_ID)
VALUES(1213, 10);


INSERT INTO WEGETHER.TBL_COMMUNITY_FILE
(ID, COMMUNITY_ID)
VALUES(1214, 10);


INSERT INTO WEGETHER.TBL_COMMUNITY_FILE
(ID, COMMUNITY_ID)
VALUES(1215, 10);


INSERT INTO WEGETHER.TBL_COMMUNITY_FILE
(ID, COMMUNITY_ID)
VALUES(1216, 11);


INSERT INTO WEGETHER.TBL_COMMUNITY_FILE
(ID, COMMUNITY_ID)
VALUES(1217, 11);


INSERT INTO WEGETHER.TBL_COMMUNITY_FILE
(ID, COMMUNITY_ID)
VALUES(1218, 11);


INSERT INTO WEGETHER.TBL_COMMUNITY_FILE
(ID, COMMUNITY_ID)
VALUES(1219, 12);


INSERT INTO WEGETHER.TBL_COMMUNITY_FILE
(ID, COMMUNITY_ID)
VALUES(1220, 13);

INSERT INTO WEGETHER.TBL_COMMUNITY_FILE
(ID, COMMUNITY_ID)
VALUES(1221, 14);

INSERT INTO WEGETHER.TBL_COMMUNITY_FILE
(ID, COMMUNITY_ID)
VALUES(1222, 15);

INSERT INTO WEGETHER.TBL_COMMUNITY_FILE
(ID, COMMUNITY_ID)
VALUES(1223, 15);

INSERT INTO WEGETHER.TBL_COMMUNITY_FILE
(ID, COMMUNITY_ID)
VALUES(1224, 15);

