/*자료 찜목록 테이블 생성*/

CREATE SEQUENCE SEQ_WISH_DATA;

CREATE TABLE TBL_WISH_DATA(
	ID NUMBER CONSTRAINT PK_WISH_DATA PRIMARY KEY,
	MEMBER_ID NUMBER NOT NULL,
	DATA_ID NUMBER NOT NULL
);

SELECT * FROM TBL_WISH_DATA;

DROP TABLE TBL_WISH_DATA;

/*DATA 테이블 FK 설정*/
	ALTER TABLE TBL_WISH_DATA ADD CONSTRAINT FK_WISH_DATA_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID);

	ALTER TABLE TBL_WISH_DATA ADD CONSTRAINT FK_WISH_DATA_DATA FOREIGN KEY(DATA_ID)
	REFERENCES TBL_DATA(ID);

/*소영 데이터 찜하기*/
INSERT INTO TBL_WISH_DATA
(ID, MEMBER_ID, DATA_ID)
VALUES(SEQ_WISH_DATA.NEXTVAL ,100, 1000);
