/*�봽濡쒖젥�듃 �뀒�씠釉� �깮�꽦*/
CREATE SEQUENCE SEQ_PROJECT;

DROP TABLE TBL_PROJECT;

CREATE TABLE TBL_PROJECT(
	ID NUMBER CONSTRAINT PK_PROJECT PRIMARY KEY,
	MEMBER_ID NUMBER NOT NULL,
	PROJECT_TITLE VARCHAR2(1000) NOT NULL,
	PROJECT_INTRODUCING VARCHAR2(1000) NOT NULL,
	PROJECT_MAJOR VARCHAR2(1000) NOT NULL,
	PROJECT_SCHOOL VARCHAR2(1000) NOT NULL,
	PROJECT_REGISTER_DATE DATE DEFAULT SYSDATE,
	PROJECT_UPDATE_DATE DATE DEFAULT SYSDATE,
	PROJECT_END_DATE VARCHAR2(1000) NOT NULL,
	PROJECT_READ_COUNT NUMBER DEFAULT 0,
	PROJECT_NOW_PERSONNEL NUMBER DEFAULT 0,
	PROJECT_TOTAL_PERSONNEL NUMBER NOT NULL
)

SELECT * FROM TBL_PROJECT;

--------------------------------------------------------- TBL_PROJECT -----------------------------------------------------------------------------

INSERT INTO WEGETHER.TBL_PROJECT
(ID, MEMBER_ID, PROJECT_TITLE, PROJECT_INTRODUCING, PROJECT_MAJOR, PROJECT_SCHOOL, PROJECT_REGISTER_DATE, PROJECT_UPDATE_DATE, PROJECT_END_DATE, PROJECT_READ_COUNT, PROJECT_NOW_PERSONNEL, PROJECT_TOTAL_PERSONNEL)
VALUES(SEQ_PROJECT.NEXTVAL, 25, '브랜드마케팅프로젝트', '브랜드마케팅을전문으로하는프로젝트입니다', '전공무관', '경희대학교', SYSDATE, SYSDATE, '2023-06-19', 2, 5, 10);

INSERT INTO WEGETHER.TBL_PROJECT
(ID, MEMBER_ID, PROJECT_TITLE, PROJECT_INTRODUCING, PROJECT_MAJOR, PROJECT_SCHOOL, PROJECT_REGISTER_DATE, PROJECT_UPDATE_DATE, PROJECT_END_DATE, PROJECT_READ_COUNT, PROJECT_NOW_PERSONNEL, PROJECT_TOTAL_PERSONNEL)
VALUES(SEQ_PROJECT.NEXTVAL, 25, 'SNS디자인 및 운영 프로젝트', 'SNS디자인과 운영을 전문적으로 관리하고 만드는 프로젝트입니다', '전공무관', '고려대학교', SYSDATE, SYSDATE, '2023-06-19', 2, 2, 8);

INSERT INTO WEGETHER.TBL_PROJECT
(ID, MEMBER_ID, PROJECT_TITLE, PROJECT_INTRODUCING, PROJECT_MAJOR, PROJECT_SCHOOL, PROJECT_REGISTER_DATE, PROJECT_UPDATE_DATE, PROJECT_END_DATE, PROJECT_READ_COUNT, PROJECT_NOW_PERSONNEL, PROJECT_TOTAL_PERSONNEL)
VALUES(SEQ_PROJECT.NEXTVAL, 25, '영상제작 및 편집 프로젝트', '영상을 제작하고 편집하는 것을 전문적으로 하는 프로젝트입니다', '영상관련전공', '중앙대학교', SYSDATE, SYSDATE, '2023-06-19', 2, 2, 8);

INSERT INTO WEGETHER.TBL_PROJECT
(ID, MEMBER_ID, PROJECT_TITLE, PROJECT_INTRODUCING, PROJECT_MAJOR, PROJECT_SCHOOL, PROJECT_REGISTER_DATE, PROJECT_UPDATE_DATE, PROJECT_END_DATE, PROJECT_READ_COUNT, PROJECT_NOW_PERSONNEL, PROJECT_TOTAL_PERSONNEL)
VALUES(SEQ_PROJECT.NEXTVAL, 25, '자소서 첨삭 및 학업계획 프로젝트', '자소서 첨삭 및 학업계획을 관리해주는 프로젝트입니다', '전공무관', '학력무관', SYSDATE, SYSDATE, '2023-06-19', 10, 15, 30);

INSERT INTO WEGETHER.TBL_PROJECT
(ID, MEMBER_ID, PROJECT_TITLE, PROJECT_INTRODUCING, PROJECT_MAJOR, PROJECT_SCHOOL, PROJECT_REGISTER_DATE, PROJECT_UPDATE_DATE, PROJECT_END_DATE, PROJECT_READ_COUNT, PROJECT_NOW_PERSONNEL, PROJECT_TOTAL_PERSONNEL)
VALUES(SEQ_PROJECT.NEXTVAL, 25, '예비 고1을 위한 프로젝트', '앞으로의 학교생활 성공적인 고등학교 생활을 원하는 학생들을 위한 프로젝트입니다', '전공무관', '학력무관', SYSDATE, SYSDATE, '2023-07-19', 15, 20, 50);

INSERT INTO WEGETHER.TBL_PROJECT
(ID, MEMBER_ID, PROJECT_TITLE, PROJECT_INTRODUCING, PROJECT_MAJOR, PROJECT_SCHOOL, PROJECT_REGISTER_DATE, PROJECT_UPDATE_DATE, PROJECT_END_DATE, PROJECT_READ_COUNT, PROJECT_NOW_PERSONNEL, PROJECT_TOTAL_PERSONNEL)
VALUES(SEQ_PROJECT.NEXTVAL, 25, '초보자도 가능한 드로잉 프로젝트', '드로잉을 배우시고 싶으신분들을 위한 프로젝트입니다', '전공무관', '학력무관', SYSDATE, SYSDATE, '2023-07-19', 10, 5, 15);

INSERT INTO WEGETHER.TBL_PROJECT
(ID, MEMBER_ID, PROJECT_TITLE, PROJECT_INTRODUCING, PROJECT_MAJOR, PROJECT_SCHOOL, PROJECT_REGISTER_DATE, PROJECT_UPDATE_DATE, PROJECT_END_DATE, PROJECT_READ_COUNT, PROJECT_NOW_PERSONNEL, PROJECT_TOTAL_PERSONNEL)
VALUES(SEQ_PROJECT.NEXTVAL, 25, '다이어트를 위한 프로젝트', '좋은 몸을 만드시고 싶으신가요? 여러분들을 위한 프로젝트입니다', '전공무관', '학력무관', SYSDATE, SYSDATE, '2023-06-19', 10, 25, 50);

INSERT INTO WEGETHER.TBL_PROJECT
(ID, MEMBER_ID, PROJECT_TITLE, PROJECT_INTRODUCING, PROJECT_MAJOR, PROJECT_SCHOOL, PROJECT_REGISTER_DATE, PROJECT_UPDATE_DATE, PROJECT_END_DATE, PROJECT_READ_COUNT, PROJECT_NOW_PERSONNEL, PROJECT_TOTAL_PERSONNEL)
VALUES(SEQ_PROJECT.NEXTVAL, 25, '노래를 잘 하고 싶으신 분들을 위한 프로젝트', '노래를 잘하고싶으신가요? 음치를 고치고 싶으신가요? 참여하세요', '전공무관', '학력무관', SYSDATE, SYSDATE, '2023-06-19', 10, 15, 30);

INSERT INTO WEGETHER.TBL_PROJECT
(ID, MEMBER_ID, PROJECT_TITLE, PROJECT_INTRODUCING, PROJECT_MAJOR, PROJECT_SCHOOL, PROJECT_REGISTER_DATE, PROJECT_UPDATE_DATE, PROJECT_END_DATE, PROJECT_READ_COUNT, PROJECT_NOW_PERSONNEL, PROJECT_TOTAL_PERSONNEL)
VALUES(SEQ_PROJECT.NEXTVAL, 25, '투자 및 트레이딩 프로젝트', '투자를 잘 하고싶으신가요? 트레이딩을 배우고싶으신가요?', '전공무관', '학력무관', SYSDATE, SYSDATE, '2023-06-19', 50, 8, 10);

INSERT INTO WEGETHER.TBL_PROJECT
(ID, MEMBER_ID, PROJECT_TITLE, PROJECT_INTRODUCING, PROJECT_MAJOR, PROJECT_SCHOOL, PROJECT_REGISTER_DATE, PROJECT_UPDATE_DATE, PROJECT_END_DATE, PROJECT_READ_COUNT, PROJECT_NOW_PERSONNEL, PROJECT_TOTAL_PERSONNEL)
VALUES(SEQ_PROJECT.NEXTVAL, 25, '패션을 알려드리는 프로젝트', '옷을 어떻게 입어야할지 모르시나요? 패알못들을 위한 프로젝트가 왔습니다', '전공무관', '학력무관', SYSDATE, SYSDATE, '2023-06-19', 10, 15, 30);


-------------------------------------------------------- TBL_FILE -----------------------------------------------------

INSERT INTO WEGETHER.TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1102   ,2023-05-29, 'kuXTM1631735405', 'SNS디자인.png', 55, 'REPRESENTATIVE')

INSERT INTO WEGETHER.TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1103   ,2023-05-29, 'rCwiM1681629353', '브랜드마케팅.png', 55, 'REPRESENTATIVE')

INSERT INTO WEGETHER.TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1104   ,2023-05-29, 'customprojectcategory253', '영상제작및편집.png', 55, 'REPRESENTATIVE')

INSERT INTO WEGETHER.TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1105   ,2023-05-29, 'basvg1640916880', '자소서 첨삭 및 학업계획.png', 55, 'REPRESENTATIVE')

INSERT INTO WEGETHER.TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1106   ,2023-05-29, 'Ki1GP1642596662', '예비 고1.png', 55, 'REPRESENTATIVE')

INSERT INTO WEGETHER.TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1107   ,2023-05-29, 'efkuQ1679470652', '초보자도 가능한 드로잉.png', 55, 'REPRESENTATIVE')

INSERT INTO WEGETHER.TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1108   ,2023-05-29, 'YiQNF1607941521', '다이어트.png', 55, 'REPRESENTATIVE')

INSERT INTO WEGETHER.TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1109   ,2023-05-29, '1K2oG1671721392', '노래.png', 55, 'REPRESENTATIVE')

INSERT INTO WEGETHER.TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1110   ,2023-05-29, 'DpUeX1684825917', '투자 및 트레이딩.png', 55, 'REPRESENTATIVE')

INSERT INTO WEGETHER.TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1111   ,2023-05-30, 'y5DwG1626415602', '패션.png', 55, 'REPRESENTATIVE')

SELECT * FROM TBL_FILE

----------------------------------------------------- TBL_PROJECT_FILE --------------------------------------------------


INSERT INTO WEGETHER.TBL_PROJECT_FILE
(ID, PROJECT_ID)
VALUES(1102, 23);

INSERT INTO WEGETHER.TBL_PROJECT_FILE
(ID, PROJECT_ID)
VALUES(1103, 24);

INSERT INTO WEGETHER.TBL_PROJECT_FILE
(ID, PROJECT_ID)
VALUES(1104, 25);

INSERT INTO WEGETHER.TBL_PROJECT_FILE
(ID, PROJECT_ID)
VALUES(1105, 26);

INSERT INTO WEGETHER.TBL_PROJECT_FILE
(ID, PROJECT_ID)
VALUES(1106, 27);

INSERT INTO WEGETHER.TBL_PROJECT_FILE
(ID, PROJECT_ID)
VALUES(1107, 28);

INSERT INTO WEGETHER.TBL_PROJECT_FILE
(ID, PROJECT_ID)
VALUES(1108, 29);

INSERT INTO WEGETHER.TBL_PROJECT_FILE
(ID, PROJECT_ID)
VALUES(1109, 30);

INSERT INTO WEGETHER.TBL_PROJECT_FILE
(ID, PROJECT_ID)
VALUES(1110, 31);

INSERT INTO WEGETHER.TBL_PROJECT_FILE
(ID, PROJECT_ID)
VALUES(1111, 32);


/*�봽濡쒖젥�듃 FK �꽕�젙*/
	ALTER TABLE TBL_PROJECT ADD CONSTRAINT FK_PROJECT_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID);
	


/*TBL_PROJECT_FILE �뀒�씠釉� �깮�꽦*/
CREATE SEQUENCE SEQ_PROJECT_FILE;

DROP TABLE TBL_PROJECT_FILE;

CREATE TABLE TBL_PROJECT_FILE(
	ID NUMBER CONSTRAINT PK_PROJECT_FILE PRIMARY KEY,
	PROJECT_ID NUMBER NOT NULL
)

SELECT * FROM TBL_PROJECT_FILE;


/*TBL_PROJECT_FILE �뀒�씠釉� FK �꽕�젙*/
	ALTER TABLE TBL_PROJECT_FILE ADD CONSTRAINT FK_PROJECT_FILE_FILE FOREIGN KEY(ID)
	REFERENCES TBL_FILE(ID);

	ALTER TABLE TBL_PROJECT_FILE ADD CONSTRAINT FK_PROJECT_FILE_PROJECT FOREIGN KEY(PROJECT_ID)
	REFERENCES TBL_PROJECT(ID);

INSERT INTO WEGETHER.TBL_PROJECT
(ID, MEMBER_ID, PROJECT_TITLE, PROJECT_INTRODUCING, PROJECT_MAJOR, PROJECT_SCHOOL, PROJECT_REGISTER_DATE, PROJECT_UPDATE_DATE, PROJECT_END_DATE, PROJECT_READ_COUNT, PROJECT_NOW_PERSONNEL, PROJECT_TOTAL_PERSONNEL)
VALUES(94, 100, '브랜드마케팅프로젝트', '브랜드마케팅을전문으로하는프로젝트입니다', '전공무관', '경희대학교', SYSDATE, SYSDATE, '2023-06-19', 2, 5, 10);

INSERT INTO WEGETHER.TBL_PROJECT
(ID, MEMBER_ID, PROJECT_TITLE, PROJECT_INTRODUCING, PROJECT_MAJOR, PROJECT_SCHOOL, PROJECT_REGISTER_DATE, PROJECT_UPDATE_DATE, PROJECT_END_DATE, PROJECT_READ_COUNT, PROJECT_NOW_PERSONNEL, PROJECT_TOTAL_PERSONNEL)
VALUES(95, 100, 'SNS디자인및운영프로젝트', 'SNS디자인과 운영을 전문적으로 관리하고 만드는 프로젝트입니다', '전공무관', '고려대학교', SYSDATE, SYSDATE, '2023-06-19', 2, 2, 8);

INSERT INTO WEGETHER.TBL_PROJECT
(ID, MEMBER_ID, PROJECT_TITLE, PROJECT_INTRODUCING, PROJECT_MAJOR, PROJECT_SCHOOL, PROJECT_REGISTER_DATE, PROJECT_UPDATE_DATE, PROJECT_END_DATE, PROJECT_READ_COUNT, PROJECT_NOW_PERSONNEL, PROJECT_TOTAL_PERSONNEL)
VALUES(96, 100, '영상제작및편집프로젝트', '영상을 제작하고 편집하는 것을 전문적으로 하는 프로젝트입니다', '영상관련전공', '중앙대학교', SYSDATE, SYSDATE, '2023-06-19', 2, 2, 8);

INSERT INTO WEGETHER.TBL_PROJECT
(ID, MEMBER_ID, PROJECT_TITLE, PROJECT_INTRODUCING, PROJECT_MAJOR, PROJECT_SCHOOL, PROJECT_REGISTER_DATE, PROJECT_UPDATE_DATE, PROJECT_END_DATE, PROJECT_READ_COUNT, PROJECT_NOW_PERSONNEL, PROJECT_TOTAL_PERSONNEL)
VALUES(97, 100, '자소서첨삭및학업계획프로젝트', '자소서 첨삭 및 학업계획을 관리해주는 프로젝트입니다', '전공무관', '학력무관', SYSDATE, SYSDATE, '2023-06-19', 10, 15, 30);

INSERT INTO WEGETHER.TBL_PROJECT
(ID, MEMBER_ID, PROJECT_TITLE, PROJECT_INTRODUCING, PROJECT_MAJOR, PROJECT_SCHOOL, PROJECT_REGISTER_DATE, PROJECT_UPDATE_DATE, PROJECT_END_DATE, PROJECT_READ_COUNT, PROJECT_NOW_PERSONNEL, PROJECT_TOTAL_PERSONNEL)
VALUES(98, 100, '예비고1을위한프로젝트', '앞으로의 학교생활 성공적인 고등학교 생활을 원하는 학생들을 위한 프로젝트입니다', '전공무관', '학력무관', SYSDATE, SYSDATE, '2023-07-19', 15, 20, 50);

INSERT INTO WEGETHER.TBL_PROJECT
(ID, MEMBER_ID, PROJECT_TITLE, PROJECT_INTRODUCING, PROJECT_MAJOR, PROJECT_SCHOOL, PROJECT_REGISTER_DATE, PROJECT_UPDATE_DATE, PROJECT_END_DATE, PROJECT_READ_COUNT, PROJECT_NOW_PERSONNEL, PROJECT_TOTAL_PERSONNEL)
VALUES(99, 100, '초보자도가능한드로잉프로젝트', '드로잉을 배우시고 싶으신분들을 위한 프로젝트입니다', '전공무관', '학력무관', SYSDATE, SYSDATE, '2023-07-19', 10, 5, 15);

INSERT INTO WEGETHER.TBL_PROJECT
(ID, MEMBER_ID, PROJECT_TITLE, PROJECT_INTRODUCING, PROJECT_MAJOR, PROJECT_SCHOOL, PROJECT_REGISTER_DATE, PROJECT_UPDATE_DATE, PROJECT_END_DATE, PROJECT_READ_COUNT, PROJECT_NOW_PERSONNEL, PROJECT_TOTAL_PERSONNEL)
VALUES(100, 100, '다이어트를위한프로젝트', '좋은 몸을 만드시고 싶으신가요? 여러분들을 위한 프로젝트입니다', '전공무관', '학력무관', SYSDATE, SYSDATE, '2023-06-19', 10, 25, 50);

INSERT INTO WEGETHER.TBL_PROJECT
(ID, MEMBER_ID, PROJECT_TITLE, PROJECT_INTRODUCING, PROJECT_MAJOR, PROJECT_SCHOOL, PROJECT_REGISTER_DATE, PROJECT_UPDATE_DATE, PROJECT_END_DATE, PROJECT_READ_COUNT, PROJECT_NOW_PERSONNEL, PROJECT_TOTAL_PERSONNEL)
VALUES(101, 100, '노래를잘하고싶으신분들을위한프로젝트', '노래를 잘하고싶으신가요? 음치를 고치고 싶으신가요? 참여하세요', '전공무관', '학력무관', SYSDATE, SYSDATE, '2023-06-19', 10, 15, 30);

INSERT INTO WEGETHER.TBL_PROJECT
(ID, MEMBER_ID, PROJECT_TITLE, PROJECT_INTRODUCING, PROJECT_MAJOR, PROJECT_SCHOOL, PROJECT_REGISTER_DATE, PROJECT_UPDATE_DATE, PROJECT_END_DATE, PROJECT_READ_COUNT, PROJECT_NOW_PERSONNEL, PROJECT_TOTAL_PERSONNEL)
VALUES(102, 100, '투자및트레이딩프로젝트', '투자를 잘 하고싶으신가요? 트레이딩을 배우고싶으신가요?', '전공무관', '학력무관', SYSDATE, SYSDATE, '2023-06-19', 50, 8, 10);

INSERT INTO WEGETHER.TBL_PROJECT
(ID, MEMBER_ID, PROJECT_TITLE, PROJECT_INTRODUCING, PROJECT_MAJOR, PROJECT_SCHOOL, PROJECT_REGISTER_DATE, PROJECT_UPDATE_DATE, PROJECT_END_DATE, PROJECT_READ_COUNT, PROJECT_NOW_PERSONNEL, PROJECT_TOTAL_PERSONNEL)
VALUES(103, 100, '패션을알려드리는프로젝트', '옷을 어떻게 입어야할지 모르시나요? 패알못들을 위한 프로젝트가 왔습니다', '전공무관', '학력무관', SYSDATE, SYSDATE, '2023-06-19', 10, 15, 30);








